add path creation if not exist
Signed-off-by: Guillaume Falourd <guillaume.falourd@zup.com.br>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,8 +26,10 @@ runs:
             echo "No path to clone provided."
         else
             if [ ! -d "${{ inputs.path-to-clone }}" ]; then
-                echo "PATH ${{ inputs.path-to-clone }} DOES NOT exist in the workspace: ${{ github.workspace }}"
-                exit 1
+                mkdir ${{ inputs.path-to-clone }}
+                if [ ! -d "${{ inputs.path-to-clone }}" ]; then
+                    echo "PATH ${{ inputs.path-to-clone }} DOES NOT exist in the workspace: ${{ github.workspace }} and couldn't be created automatically."
+                    exit 1
             fi
         fi
         
